import{a as S,S as q,i as c}from"./assets/vendor-C2ySes1p.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const B="https://pixabay.com/api/",$="55189993-ff866a9899946a4c222a471fa";async function f(o,t=1){const s={key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await S.get(B,{params:s})).data}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),p=document.querySelector(".load-more"),E=new q(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const t=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:n,comments:b,downloads:w})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${s}" alt="${e}" />
        </a>
        <div class="info">
          <p>Likes: ${r}</p>
          <p>Views: ${n}</p>
          <p>Comments: ${b}</p>
          <p>Downloads: ${w}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",t),E.refresh()}function M(){m.innerHTML=""}function g(){y.classList.add("is-visible")}function L(){y.classList.remove("is-visible")}function v(){p.classList.remove("is-hidden")}function l(){p.classList.add("is-hidden")}const O=document.querySelector(".form"),P=document.querySelector(".load-more");let d="",a=1,u=0;O.addEventListener("submit",async o=>{if(o.preventDefault(),d=o.target.elements.search.value.trim(),!!d){a=1,M(),l(),g();try{const t=await f(d,a);if(u=t.totalHits,t.hits.length===0){c.error({message:"Sorry, no images found."});return}h(t.hits),v(),a*15>=u&&(l(),c.info({message:"We're sorry, but you've reached the end of search results."}))}catch{c.error({message:"Error fetching images"})}finally{L()}}});P.addEventListener("click",async()=>{a+=1,l(),g();try{const o=await f(d,a);h(o.hits);const t=document.querySelector(".gallery-item");if(t){const s=t.getBoundingClientRect();window.scrollBy({top:s.height*2,behavior:"smooth"})}a*15<u?v():(l(),c.info({message:"We're sorry, but you've reached the end of search results."}))}catch{c.error({message:"Error loading more images"})}finally{L()}});l();
//# sourceMappingURL=index.js.map
